name: fanastic_assistant
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  firebase_messaging: ^14.6.5
  flutter_bloc: ^8.1.3
  carousel_slider: ^4.2.1
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0





flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/

  fonts:
    - family: SpaceGrotesk
      fonts:
      - asset: lib/assets/fonts/SpaceGrotesk/SpaceGrotesk-Light.ttf
        weight: 300
      - asset: lib/assets/fonts/SpaceGrotesk/SpaceGrotesk-Regular.ttf
        weight: 400
      - asset: lib/assets/fonts/SpaceGrotesk/SpaceGrotesk-Medium.ttf
        weight: 500
      - asset: lib/assets/fonts/SpaceGrotesk/SpaceGrotesk-SemiBold.ttf
        weight: 600
      - asset: lib/assets/fonts/SpaceGrotesk/SpaceGrotesk-Bold.ttf
        weight: 700